#!/usr/bin/env python3
# Dummy bundle file generated by testeranto
# Hash: d03d931034924edbfb591bc2429102fa
# This file loads and executes the original test file: /workspace/src/python/Calculator.pitono.test.py

import sys
import os

# Add the original file's directory to sys.path if needed
original_dir = os.path.dirname(r'/workspace/src/python/Calculator.pitono.test.py')
if original_dir not in sys.path:
    sys.path.insert(0, original_dir)

# Load and execute the original test file
# Using exec to ensure execution every time
with open(r'/workspace/src/python/Calculator.pitono.test.py', 'r', encoding='utf-8') as f:
    code = f.read()

# Execute the code in the global namespace
exec(code, {'__name__': '__main__', '__file__': r'/workspace/src/python/Calculator.pitono.test.py'})

# If the test framework requires explicit test execution, add it here
# For example:
#   if 'TestFramework' in locals():
#       TestFramework.run()
