# Dummy bundle file generated by testeranto
# Hash: 1bba1e3b3698b0a0b9c3b8703d5bdf59
# This file loads and executes the original test file: src/ruby/Calculator-test.rb

# Add the original file's directory to load path if needed
original_dir = File.dirname('/workspace/src/ruby/Calculator-test.rb')
$LOAD_PATH.unshift(original_dir) unless $LOAD_PATH.include?(original_dir)

# Load and execute the original test file
# Using load instead of require ensures execution every time
load '/workspace/src/ruby/Calculator-test.rb'

# If the test framework requires explicit test execution, add it here
# For example:
#   TestFramework.run if defined?(TestFramework)
# This depends on the specific test framework being used
