#!/usr/bin/env ruby
# This file is generated by the ruby builder
# It executes the actual Calculator test

require 'json'

# Build the test resource configuration
# config = {
#   name: "test_name",
#   fs: '.',
#   ports: [],
#   timeout: 30000,
#   retries: 0,
#   environment: {}
# }.to_json

# Execute the test file directly with the configuration
exec("ruby", "../../../../../example/Calculator-test.rb", config)
